version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TRUSTED_ORIGINS: ${NEXT_PUBLIC_APP_URL}

  ai:
    build:
      context: .
      dockerfile: Dockerfile.ai

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:2222
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - backend
